
let $ITstack = 'D:/Dropbox/JH/core/IT_stack'
  let $onGH = $ITstack.'/onGitHub'
    let $MSwin = $onGH.'/MSWin10'
    let $SPDHPP = $onGH.'/SyncPortableDrives\HPP'

" Point to my Win10 vimrc:
source $HOME/vimfiles/vimrc-Win10.vim

