#!/bin/bash
# vim: set fdl=2 sw=2:

# $MSn/WSL/bash_profile (see  \\wsl$\Ubuntu\etc\skel\.profile)
#  setup in  $MSn/set/8-WSL-symlinks.sh
# relaunch  Ubuntu  if any changes here

# private bin
if [ -d "$HOME/bin" ] ; then PATH="$HOME/bin:$PATH"; fi
if [ -d "$HOME/.local/bin" ] ; then PATH="$HOME/.local/bin:$PATH"; fi

#=> 0 exports
export host=$(uname -n)
export WSL=yes

#==> places
# check against  $OSAB/nodes-Bash/export-storage
export Drpbx=/mnt/d/Dropbox
  export DJH=$Drpbx/JH
    export core=$DJH/core
      export coreIT=$core/IT
        export CrPl=$cITCP  # $cITCP
        export MSWml=$coreIT/MSWin/ml-$host  # $MSWml
        export onGH=$coreIT/onGitHub
          export MSwin10=$onGH/OS-MSWin10
            export MSn=$MSWin10/nodes
            export MSWSL=$MSn/WSL
          export OSAB=$onGH/OS-ArchBuilds
            export ABjo=$OSAB/nodes-jo
              export AjB=$ABjo/Bash
          export OSL=$onGH/OS-Linux
              export clMail="$OSL/nodes/jo/clm"
                export clMn=$clMail/neomutt
          export vimfiles=$onGH/vimfiles
        export culL=$coreIT/ulLinux
          export culLA=$culL/Arch
export maild=/home/jo/.local/share/mail  # $maild  for  mutt

#=> 1 bashrc
source $OSL/nodes/jo/export
source ~/.bashrc  # works in  tmux ($MSn/WSL/bashrc)

