#!/bin/bash
# vim: set fdl=2 sw=2:

# $MSn/WSL/bash_profile (see  \\wsl$\Ubuntu\etc\skel\.profile)
#  setup in  $MSn/set/8-WSL-symlinks.sh
# relaunch  Ubuntu  if any changes here

# private bin
if [ -d "$HOME/bin" ] ; then PATH="$HOME/bin:$PATH"; fi
if [ -d "$HOME/.local/bin" ] ; then PATH="$HOME/.local/bin:$PATH"; fi

#=> 0 exports
export host=$(uname -n)

#==> places
# check against  $OSAB/Bash/export-storage
export Drpbx=/mnt/d/Dropbox
  export DJH=$Drpbx/JH
    export core=$DJH/core
      export ITstack=$core/IT_stack
        export CrPl=$ITstack/CP  # $CrPl
        export machLg=$ITstack/MSWin/ml-$host  # $machLg
        export onGH=$ITstack/onGitHub
          export MSwin10=$onGH/OS-MSWin10
            export MSn=$MSWin10/nodes
            export MSWSL=$MSn/WSL
          export OSAB=$onGH/OS-ArchBuilds
            export ABjo=$OSAB/jo
              export AjB=$ABjo/Bash
          export OSL=$onGH/OS-Linux
          export vimfiles=$onGH/vimfiles
        export ulL=$ITstack/unix_like-linux
          export ulLA=$ulL/Arch

#=> 1 bashrc
source $OSL/export-jo
source ~/.bashrc  # works in  tmux ($MSn/WSL/bashrc)

