#!/bin/bash
# vim: set sw=2:

# $MSn/WSL/bash_profile
#  setup in  $MSn/set/8-WSL-symlinks.sh
#  sourced by  $MSn/WSL/bash_profile

#  also there is  \\wsl$\Ubuntu\etc\profile

alias u=tmux
source $OSL/bashrc-console-fm
source $OSL/bashrc-generic

lnd () { [ -d $2 ] && rm -r $2; ln -sf $1 $2; } # symlink a directory
[[ $TERM == 'xterm-256color' ]] && neofetch

se () {
  echo -n "${tpf2}aliases:${tpfn}  "; compgen -a | awk '{print}' ORS=' : '; echo ''
  echo -n "${tpf2}builtins:${tpfn} "; compgen -b | awk '{print}' ORS=' : '; echo ''
  echo -n "${tpf2}commands:${tpfn} "; compgen -c | awk '{print}' ORS=' : '; echo '' # long time
}

#=> better file managing
alias fd=fdfind
alias fe='pwsh.exe -nop -c start .'  # File Explorer here
if [ -s "/var/snap/jump" ]; then eval "$(jump shell)"; fi # gsamokovarov's jump

c() { if [ -n "$1" ]; then cd "$1" || return 1; else cd ..; fi; ls -a; }
# less  is somehow the default pager

if [ -s "/usr/bin/fzf" ]; then
  alias f="fzf --preview 'highlight -O truecolor {}'"  # tajmone/highlight
  export FZF_DEFAULT_COMMAND='fdfind --type f --hidden --follow --exclude .git --no-ignore'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  source /usr/share/bash-completion/completions/fzf
  # = \\wsl$\Ubuntu\usr\share\bash-completion\completions\fzf
  source /usr/share/doc/fzf/examples/key-bindings.bash
  # = \\wsl$\Ubuntu\usr\share\doc\fzf\examples\key-bindings.bash
fi

#=> Bash interface
alias o=echo

# for nnn & tmux
export EDITOR=nvim
export VISUAL=gvim

#==> prompt
source /usr/lib/git-core/git-sh-prompt; source $OSL/bashrc-console-prompt

#=> exports
export eup=$(wslpath $(cmd.exe /C "echo %USERPROFILE%" 2>/dev/null | tr -d '\r'))
  export Enc=$eup/encrypted

#=> from  \\wsl$\Ubuntu\etc\skel\.bashrc
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable color support of ls and also add handy aliases:
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
# and then override with fancy colouring
[ $ITscc ] && source $ITscc/forArch/trapd00r-LS_COLORS/lscolors.sh  # o "$LS_COLORS"

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# enable programmable completion features
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion  # \\wsl$\Ubuntu\etc\bash.bashrc
    fi
  fi

