
let $DROPBOX = $HOME.'\Dropbox'  " keep this capitalised for finding it without need for $
  let $core = $DROPBOX.'\JH\core'
    let $ITstack = $core.'\IT_stack'
      let $CrPl = $ITstack.'\CrossPlatform'
      let $onGH = $ITstack.'\onGitHub'
        let $MSwin10 = $onGH.'\MSWin10'
          let $machine = $MSwin10.'\T430i73520M'
" more locations are defined in  $onGH\vimfiles\vimrc-Win10.vim
let $USER = 'troin'

let mapleader='#'  " because  T430i73520M  has no  \
source $HOME\vimfiles\vimrc-Win10.vim

