
let $DROPBOX = $HOME.'/Dropbox'  " keep this capitalised for finding it without need for $
  let $core = $DROPBOX.'/JH/core'
    let $ITstack = $core.'/IT_stack'
      let $CP = $ITstack.'/CrossPlatform'
      let $onGH = $ITstack.'/onGitHub'
        let $MSwin10 = $onGH.'/MSWin10'
          let $machine = $MSwin10.'/T430i73520M'
" more locations are defined in  $onGH/vimfiles/vimrc-Win10.vim

let mapleader='#'
source $HOME/vimfiles/vimrc-Win10.vim

set pythonthreedll=C:\Users\troin\AppData\Local\Programs\Python\Python310-32\python310.dll

