#!/bin/bash
# vim: set fdl=2 sw=2:

# $MSWSL\bash_profile (see  \\wsl$\Ubuntu\etc\skel\.profile)

# setup steps
#  rm ~/.profile
#  rm ~/.bash_profile
#  cp /mnt/d/Dropbox/JH/core/IT_stack/onGitHub/OS-MSWin10/WSL/bash_profile ~/.bash_profile
#  bash $MSWSL/bs-symlinks.sh

# . "$HOME/.bashrc"

# private bin
if [ -d "$HOME/bin" ] ; then PATH="$HOME/bin:$PATH"; fi
if [ -d "$HOME/.local/bin" ] ; then PATH="$HOME/.local/bin:$PATH"; fi

#=> 0 exports
export host=$(uname -n)

#==> places
# check against  $OSAB/Bash/export-storage
export Drpbx=/mnt/d/Dropbox
  export DJH=$Drpbx/JH
    export core=$DJH/core
      export ITstack=$core/IT_stack
        export CrPl=$ITstack/CP  # $CrPl
        export machLg=$ITstack/MSWin/ml-$host  # $machLg
        export onGH=$ITstack/onGitHub
          export MSwin10=$onGH/OS-MSWin10
            export MSWSL=$MSwin10/WSL
          export OSAB=$onGH/OS-ArchBuilds
            export ABjo=$OSAB/jo
              export AjB=$ABjo/Bash
          export OSL=$onGH/OS-Linux
          export vimfiles=$onGH/vimfiles
        export ulL=$ITstack/unix_like-linux
          export ulLA=$ulL/Arch

#=> 1 bashrc
source $OSL/export-jo
source ~/.bashrc  # works in  tmux

