
let $core = $HOME.'/Dropbox/JH/core'
  let $ITstack = $core.'/IT_stack'
    let $onGH = $ITstack.'/onGitHub'
      let $MSwin = $onGH.'/MSWin10'
        let $machine = $MSwin.'/LIP120s81A4'

" Point to my Win10 vimrc:
source $HOME/vimfiles/vimrc-Win10.vim

