
let $MiKTeX = $HOME.'/AppData/Roaming/MiKTeX/tex'
let $Pandoc = $HOME.'/AppData/Roaming/Pandoc'
let $ITstack = $HOME.'/Dropbox/JH/core/IT_stack'
  let $onGH = $ITstack.'/onGitHub'
    let $MD4PDF = $onGH.'/md4pdf'
    let $MSwin = $onGH.'/MSWin10'
      let $machine = $MSwin.'/LIP120s81A4'

" Point to my Win10 vimrc:
source $HOME/vimfiles/vimrc-Win10.vim

