;; vim: se ft=lisp:

;; I began here by adapting code from
;;  literatemacs  https://github.com/joseph8th/literatemacs - with thanks

;;;; 1 bootstrap  use-package
(require 'package)

;;; Set package archives
(setq package-check-signature nil)  ; because GNU ELPA keeps choking on the sigs
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-enable-at-startup nil)

(package-initialize)
(unless package-archive-contents
    (package-refresh-contents))

;;; Bootstrap use-package
(unless (package-installed-p 'use-package)
    (package-refresh-contents)
    ;; this extra line was needed
    (package-install 'use-package))

(setq use-package-verbose t)
(setq use-package-always-ensure t)
(eval-when-compile (require 'use-package))
(use-package auto-compile
    :config (auto-compile-on-load-mode))
(setq load-prefer-newer t)

;;; this block got created on first run, and gets changed as packages are included
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("e8882a809fb14f2307410a659846a06bfa58a2279ffb1f5aca0c3aecbcb6aaee" default))
 '(package-selected-packages
   '(which-key rainbow-delimiters gruvbox-theme rainbow-mode ts auto-compile use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;;; 2 settings
;; autopair
(electric-pair-mode 1)

;; Dired+
(use-package which-key)

;; set locale to UTF8
(set-language-environment 'utf-8)
(set-terminal-coding-system 'utf-8)
(setq locale-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;; ts.el - more convenient date and time library
(use-package ts)

;;; directories files
;; auto-revert to disk on file change
(global-auto-revert-mode t)

;; recentf
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)
(run-at-time nil (* 5 60) 'recentf-save-list)

;;; Emacs
;; ask "y" or "n" instead of "yes" or "no"
(defalias 'yes-or-no-p 'y-or-n-p)
;(fset 'yes-or-no-p 'y-or-n-p)

;; which-key
(use-package which-key)
(which-key-mode)

;;; layout
;; gruvbox-theme
(use-package gruvbox-theme)
  (load-theme 'gruvbox-dark-medium)

;; highlight corresponding parentheses when cursor is on one
(show-paren-mode t)

;; highlight nested parentheses
(use-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))

;; no menu along the top
(menu-bar-mode -1)
;; no shortcut buttons along the top
(tool-bar-mode 0)

;; show color codes
(use-package rainbow-mode
    :config
    (setq rainbow-x-colors nil)
    (add-hook 'prog-mode-hook 'rainbow-mode))

